import {createRequire} from 'node:module';
import {spawnSync} from 'node:child_process';
import {mkdirSync,existsSync,readFileSync} from 'node:fs';
import {parseEnv} from 'node:util';
if(existsSync('.env'))for(const [key,value] of Object.entries(parseEnv(readFileSync('.env','utf8'))))if(!process.env[key])process.env[key]=value;
process.env.SYNC_INTERVAL_MINUTES ||= '10';
process.env.WARCRAFTLOGS_ZONE_IDS ||= '1047,1048,1056';
const require=createRequire(import.meta.url);
const esbuild=require(require.resolve('esbuild',{paths:[require.resolve('drizzle-kit')]}));
mkdirSync('work',{recursive:true});
await esbuild.build({entryPoints:['scripts/standalone-entry.ts'],bundle:true,platform:'node',target:'node24',format:'esm',outfile:'work/standalone.mjs'});
const result=spawnSync(process.execPath,['work/standalone.mjs',...process.argv.slice(2)],{stdio:'inherit',env:process.env});process.exitCode=result.status??1;
